export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_EMAIL_START = 'SEND_EMAIL_START';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';
export const EMAIL_INIT = 'EMAIL_INIT';

export const FETCH_EMAILS_START = 'FETCH_EMAILS_START';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_FAIL = 'FETCH_EMAILS_FAIL';
export const FETCH_EMAILS = 'FETCH_EMAILS'